const express=require('express'),cors=require('cors'),path=require('path');require('dotenv').config();const app=express(),PORT=process.env.PORT||3000;app.use(cors());app.use(express.json({limit:'10mb'}));app.use(express.static(path.join(__dirname,'../public')));let pool;async function getPool(){if(!pool){const{Pool}=require('pg');pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false});}return pool;}async function initDB(){try{const db=await getPool();await db.query('CREATE TABLE IF NOT EXISTS clients(id SERIAL PRIMARY KEY,name VARCHAR(255) NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,channel_name VARCHAR(255),niche VARCHAR(255),created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS client_dna(id SERIAL PRIMARY KEY,client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,tone VARCHAR(100),target_audience TEXT,content_pillars TEXT,brand_voice TEXT,competitors TEXT,keywords TEXT,extra_notes TEXT,updated_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS content_tracker(id SERIAL PRIMARY KEY,client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,title VARCHAR(500),niche VARCHAR(255),search_volume INTEGER DEFAULT 0,competition VARCHAR(50),suggested_angle TEXT,status VARCHAR(50) DEFAULT \'sugerido\',created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS generated_content(id SERIAL PRIMARY KEY,client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,video_topic TEXT,titles TEXT,description TEXT,chapters TEXT,tags TEXT,email_content TEXT,thumb_brief TEXT,thumb_prompt TEXT,created_at TIMESTAMP DEFAULT NOW());');console.log('DB OK');}catch(e){console.log('DB err:',e.message);setTimeout(initDB,5000);}}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/api/clients',async(req,res)=>{try{const db=await getPool();const r=await db.query('SELECT id,name,email,channel_name,niche,created_at FROM clients ORDER BY created_at DESC');res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/clients',async(req,res)=>{const{name,email,channel_name,niche}=req.body;try{const db=await getPool();const r=await db.query('INSERT INTO clients(name,email,channel_name,niche)VALUES($1,$2,$3,$4)RETURNING *',[name,email,channel_name,niche]);res.json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/clients/:id',async(req,res)=>{try{const db=await getPool();await db.query('DELETE FROM clients WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/clients/:id/dna',async(req,res)=>{try{const db=await getPool();const r=await db.query('SELECT * FROM client_dna WHERE client_id=$1',[req.params.id]);res.json(r.rows[0]||{});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/clients/:id/dna',async(req,res)=>{const{tone,target_audience,content_pillars,brand_voice,competitors,keywords,extra_notes}=req.body;try{const db=await getPool();const ex=await db.query('SELECT id FROM client_dna WHERE client_id=$1',[req.params.id]);let r;if(ex.rows.length>0){r=await db.query('UPDATE client_dna SET tone=$1,target_audience=$2,content_pillars=$3,brand_voice=$4,competitors=$5,keywords=$6,extra_notes=$7,updated_at=NOW() WHERE client_id=$8 RETURNING *',[tone,target_audience,content_pillars,brand_voice,competitors,keywords,extra_notes,req.params.id]);}else{r=await db.query('INSERT INTO client_dna(client_id,tone,target_audience,content_pillars,brand_voice,competitors,keywords,extra_notes)VALUES($1,$2,$3,$4,$5,$6,$7,$8)RETURNING *',[req.params.id,tone,target_audience,content_pillars,brand_voice,competitors,keywords,extra_notes]);}res.json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/clients/:id/tracker',async(req,res)=>{try{const db=await getPool();const r=await db.query('SELECT * FROM content_tracker WHERE client_id=$1 ORDER BY created_at DESC',[req.params.id]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/clients/:id/tracker',async(req,res)=>{const{title,niche,search_volume,competition,suggested_angle}=req.body;try{const db=await getPool();const r=await db.query('INSERT INTO content_tracker(client_id,title,niche,search_volume,competition,suggested_angle)VALUES($1,$2,$3,$4,$5,$6)RETURNING *',[req.params.id,title,niche,search_volume||0,competition,suggested_angle]);res.json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/tracker/:id',async(req,res)=>{try{const db=await getPool();await db.query('DELETE FROM content_tracker WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/clients/:id/content',async(req,res)=>{try{const db=await getPool();const r=await db.query('SELECT * FROM generated_content WHERE client_id=$1 ORDER BY created_at DESC LIMIT 20',[req.params.id]);res.json(r.rows);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/clients/:id/content',async(req,res)=>{const{video_topic,titles,description,chapters,tags,email_content,thumb_brief,thumb_prompt}=req.body;try{const db=await getPool();const r=await db.query('INSERT INTO generated_content(client_id,video_topic,titles,description,chapters,tags,email_content,thumb_brief,thumb_prompt)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)RETURNING *',[req.params.id,video_topic,titles,description,chapters,tags,email_content,thumb_brief,thumb_prompt]);res.json(r.rows[0]);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/generate',async(req,res)=>{const{messages,system}=req.body;try{const fetch=require('node-fetch');const resp=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-5',max_tokens:3000,system:system||'',messages})});const data=await resp.json();res.json(data);}catch(e){res.status(500).json({error:e.message});}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));
app.listen(PORT,async()=>{console.log(`Studio 1i porta ${PORT}`);await initDB();});
